// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: push.proto

#include "push.pb.h"
#include "push.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace push {

static const char* PushService_method_names[] = {
  "/push.PushService/PushMessage",
};

std::unique_ptr< PushService::Stub> PushService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< PushService::Stub> stub(new PushService::Stub(channel));
  return stub;
}

PushService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_PushMessage_(PushService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status PushService::Stub::PushMessage(::grpc::ClientContext* context, const ::push::PushRequest& request, ::push::PushResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::push::PushRequest, ::push::PushResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_PushMessage_, context, request, response);
}

void PushService::Stub::experimental_async::PushMessage(::grpc::ClientContext* context, const ::push::PushRequest* request, ::push::PushResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::push::PushRequest, ::push::PushResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PushMessage_, context, request, response, std::move(f));
}

void PushService::Stub::experimental_async::PushMessage(::grpc::ClientContext* context, const ::push::PushRequest* request, ::push::PushResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PushMessage_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::push::PushResponse>* PushService::Stub::PrepareAsyncPushMessageRaw(::grpc::ClientContext* context, const ::push::PushRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::push::PushResponse, ::push::PushRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_PushMessage_, context, request);
}

::grpc::ClientAsyncResponseReader< ::push::PushResponse>* PushService::Stub::AsyncPushMessageRaw(::grpc::ClientContext* context, const ::push::PushRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPushMessageRaw(context, request, cq);
  result->StartCall();
  return result;
}

PushService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PushService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PushService::Service, ::push::PushRequest, ::push::PushResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](PushService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::push::PushRequest* req,
             ::push::PushResponse* resp) {
               return service->PushMessage(ctx, req, resp);
             }, this)));
}

PushService::Service::~Service() {
}

::grpc::Status PushService::Service::PushMessage(::grpc::ServerContext* context, const ::push::PushRequest* request, ::push::PushResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace push

